project:
  type: default
  output-dir: _output

format:
  revealjs:
    theme: [default, custom.scss]
    slide-number: true
    transition: slide
    mermaid-format: svg
    mermaid:
      theme: neutral
